#### Data science

#### List -> elements are separated by comma and enclosed with square bracket
#### heterogeneous allows mutiple data type
#### mutable
####  list cab be retrieved using index

In [2]:
sample_list=[1, 13.6, "hi", 12, 1]
sample_list

[1, 13.6, 'hi', 12, 1]

In [3]:
sample_list[0]

1

In [4]:
sample_list[-1]

1

In [5]:
sample_list[-2]

12

#### tuple 
#### heterogeneous allows mutiple data type
####  immutable changes can not be made
####  list cab be retrieved using index

In [6]:
sample_tuple=(1, 13.6 ,"hi",12, 1)
sample_tuple

[1, 13.6, 'hi', 12, 1]

In [15]:
sample_tuple[2]


IndexError: list index out of range

In [12]:
sample_tuple[1]=100

IndexError: list assignment index out of range

In [14]:
sample_tuple[1]

IndexError: list index out of range

#### Set
#### Does not allow duplicate
#### Ordered-first place
#### In set, elements cannot be retrived using index 
#### set is mutable

In [16]:
sample_set=(1,13.6,"hi", 12,127 ,25)
sample_set

(1, 13.6, 'hi', 12, 127, 25)

In [19]:
sample_set.add(1000)

AttributeError: 'tuple' object has no attribute 'add'

In [20]:
sample_set[2]

'hi'

#### Dictionary
#### has key-value pair data structure
#### key is unique
#### values can be duplicated 
#### value can be retrieved using key
#### key cannot be retrieved using index

In [21]:
sample_dict={ 1: "data",2:35.4 , 3:"data", 2:"every" }
sample_dict

{1: 'data', 2: 'every', 3: 'data'}

In [22]:
sample_dict[2]

'every'

In [23]:
sample_dict[data]

NameError: name 'data' is not defined

In [25]:
sample_dict[7]="1000"

In [26]:
sample_dict

{1: 'data', 2: 'every', 3: 'data', 7: '1000'}

In [27]:
sample_dict[10]="Business"

In [28]:
sample_dict

{1: 'data', 2: 'every', 3: 'data', 7: '1000', 10: 'Business'}

### 1 is the key and data is the value

### Numpy: Package for Multidimentional array

In [32]:
 import numpy as np

In [33]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [34]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.arange(1,10)
### dont write the "arange" function as arrange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### dont write the arange function as arrange

In [39]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [48]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#### create an array of zeros with 2 rows and 10 columns

In [54]:
np.zeros((2,10,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [55]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
np.linspace(2,20)