In [4]:
import numpy as np

In [5]:
np.random.rand(3,2)

array([[0.85276008, 0.63732655],
       [0.63854212, 0.17189241],
       [0.70701352, 0.08214134]])

In [6]:
np.random.randn(3,2)

array([[ 0.63620483, -0.28785916],
       [ 0.94779291,  0.06033779],
       [ 1.13215276, -1.56955299]])

In [7]:
np.random.randint(34,100)

75

In [8]:
np.random.randint(20,56,100)
# the entry shown that there are 100 number

array([23, 47, 47, 46, 26, 42, 33, 21, 48, 49, 50, 33, 46, 29, 34, 39, 40,
       38, 25, 53, 23, 49, 23, 31, 28, 37, 37, 52, 48, 48, 49, 55, 24, 36,
       51, 31, 20, 36, 31, 43, 46, 48, 50, 50, 28, 31, 28, 28, 53, 32, 40,
       40, 52, 30, 35, 22, 50, 55, 45, 35, 34, 39, 43, 43, 31, 50, 48, 21,
       46, 20, 43, 49, 24, 50, 38, 39, 41, 33, 27, 50, 25, 36, 52, 52, 39,
       47, 53, 47, 54, 38, 41, 42, 42, 54, 38, 34, 40, 51, 31, 28])

In [9]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
rand_array=np.random.randint(0,100,20)
rand_array

array([92, 13, 42, 43, 28, 69, 22,  3, 40, 96, 21, 19, 64, 80, 26, 22, 80,
       54, 22, 27])

In [11]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [12]:
sample_array.reshape(3,7)
# as it does not represnt the totaL NO OF THE ELEMENTS PRESESNT IN THE ARRAY

ValueError: cannot reshape array of size 30 into shape (3,7)

In [13]:
rand_array.min()

3

In [14]:
rand_array.argmin()

7

In [15]:
sample_array.dtype

dtype('int32')

In [20]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
sample_array[-3]

18

In [25]:
sample_array[3:7]

array([13, 14, 15, 16])

In [26]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [27]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [28]:
subset_sample_array=sample_array[0:7]
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [30]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [31]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two Dimensional Array

In [32]:
import numpy as np

In [33]:
sample_matrix=np.array(([30,10,3,24],[24,45,89,79],[45,89,76,56]))
sample_matrix

array([[30, 10,  3, 24],
       [24, 45, 89, 79],
       [45, 89, 76, 56]])

In [34]:
sample_matrix[0][2]

3

In [35]:
sample_matrix[2,:]

array([45, 89, 76, 56])

In [36]:
sample_matrix[2]

array([45, 89, 76, 56])

In [37]:
sample_matrix[:,(3,2)]

array([[24,  3],
       [79, 89],
       [56, 76]])

### Selection Techniques

In [39]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [40]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [41]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [42]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
np.log(sample_array)

In [ ]:
np.max(sample_array)

In [ ]:
np.min(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.argmin(sample_array)

In [ ]:
np.square(sample_array)

In [ ]:
np.std(sample_array)

In [ ]:
np.var(sample_array)

In [ ]:
np.mean(sample_array)

In [ ]:
array=np.random.randn(3,4)
array

In [ ]:
np.round(array,decimals=4)

In [ ]:
sports=np.array({cricket, fball, fball,soccer})
np.unique

### 

In [44]:
import pandas as pd
import numpy as nd

In [46]:
labels=['a','b','c','d']
sample_list=[10,20,30,40]
array=np.array([1,2,3,4])
dict={'a':100,'b':200,'c':300,'d':400}

In [47]:
pd.Series(data=sample_list)
# Series: in it S should be Capital

0    10
1    20
2    30
3    40
dtype: int64

In [48]:
pd.Series(data=sample_list, index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [50]:
pd.Series(sample_list,labels)

a    10
b    20
c    30
d    40
dtype: int64

In [51]:
pd.Series(dict)

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
### Pandas

### Pandas dataframe and indexing

In [54]:
sports1=pd.Series([10,20,30,40],index=['fball','taekondo','soccer','GT'])
sports1

fball       10
taekondo    20
soccer      30
GT          40
dtype: int64

In [55]:
sports1['GT']

40

In [ ]:
sports2=pd.Series([10,20,30,40],index=['MMA','taekondo','soccer','GT'])
sports2

In [ ]:
sports1+sports2

In [ ]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Scorecard1 Scorecard2 Scorecard3 Scorecard4 Scorecard5'.split())
df1

In [57]:
df1["scorecard3"]

NameError: name 'df1' is not defined

In [58]:
df1[["Scorecard1" "Scorecard2" "Scorecard3"]]

NameError: name 'df1' is not defined

###### 

In [ ]:
df1['Scorecard6']=df1['Scorecard1']+df1['Scorecard2']

In [ ]:
df2={'ID':['1000','1002','1003','1004','1005'],'Name':["Andy","Rose","Jade","Andrew","Emma"],'Profit':[100,200,300,400,500]}
df=pd.DataFrame(df2)
df

In [ ]:
df["ID"]

In [ ]:
df[["ID","Name",]]

In [59]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Financial-Analytics-Loan-Approval-Prediction/main/loan_prediction.csv")

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

In [ ]:
df.head(10)

In [64]:
df=pd.read_csv("https://media.githubusercontent.com/media/datablist/sample-csv-files/main/files/organizations/organizations-100.csv")

In [65]:
df.sample(10)

Index  Organization Id                            Name  \
16     17  68139b5C4De03B4       Bowers, Guerra and Krause   
85     86  B97a6CF9bf5983C                      Davila Inc   
77     78  dd6CA3d0bc3cAfc     Beasley, Greene and Mahoney   
29     30  7Cb3AeFcE4Ba31e                     Rivas Group   
39     40  AC5B7AA74Aa4A2E  Valentine, Ferguson and Kramer   
44     45  235fdEFE2cfDa5F                 Brock-Blackwell   
57     58  Bf3F3f62c8aBC33                      Cherry PLC   
78     79  A0B9d56e61070e3       Beasley, Sims and Allison   
53     54  f8D4B99e11fAF5D                        Odom Ltd   
96     97  BA6Cd9Dae2Efd62                        Good Ltd   

                               Website                  Country  \
16  http://www.carrillo-nicholson.com/                   Uganda   
85             https://mcconnell.info/  Cocos (Keeling) Islands   
77   http://www.petersen-lawrence.com/                     Togo   
29                 https://hebert.org/                Australia   
39                  http://stuart.net/                   Jersey   
44               http://www.small.com/                    Benin   
57             https://www.avila.info/         Marshall Islands   
78                  http://burke.info/                   Latvia   
53      https://www.humphrey-hess.com/            Cote d'Ivoire   
96                   http://duffy.com/                 Anguilla   

                                 Description  Founded  \
16       De-engineered transitional strategy     1972   
85            Profit-focused dedicated frame     2017   
77        Extended content-based methodology     1976   
29  Open-architected well-modulated capacity     1998   
39          Centralized secondary time-frame     1997   
44              Secured foreground emulation     1986   
57               Persistent tertiary website     1980   
78                Secured zero tolerance hub     1972   
53       Advanced static process improvement     2012   
96   Reverse-engineered composite moratorium     1971   

                         Industry  Number of employees  
16  Primary / Secondary Education                 6986  
85           Consumer Electronics                 2215  
77         Religious Institutions                  869  
29        Logistics / Procurement                 4155  
39    Non - Profit / Volunteering                 3585  
44              Online Publishing                 7034  
57                       Plastics                 8245  
78            Facilities Services                 6182  
53          Management Consulting                 1825  
96              Consumer Services                 4292

In [66]:
df.shape

(100, 9)

In [67]:
df.dtypes

Index                   int64
Organization Id        object
Name                   object
Website                object
Country                object
Description            object
Founded                 int64
Industry               object
Number of employees     int64
dtype: object

In [68]:
df.info()
# we are getting the no.of rows as same number

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Index                100 non-null    int64 
 1   Organization Id      100 non-null    object
 2   Name                 100 non-null    object
 3   Website              100 non-null    object
 4   Country              100 non-null    object
 5   Description          100 non-null    object
 6   Founded              100 non-null    int64 
 7   Industry             100 non-null    object
 8   Number of employees  100 non-null    int64 
dtypes: int64(3), object(6)
memory usage: 7.2+ KB


In [69]:
df.isnull().sum()

Index                  0
Organization Id        0
Name                   0
Website                0
Country                0
Description            0
Founded                0
Industry               0
Number of employees    0
dtype: int64

In [ ]:
df.describe